name: Trigger Azure DevOps Pipeline

on:
  push:
    branches:
      - master  

jobs:
  trigger-azure-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Azure DevOps Pipeline
        uses: azure/pipelines-action@v1
        with:
          organization: 'https://dev.azure.com/DSMidtermRepos/'  
          project: 'DSProject'  
          pipeline: '20241126.1'  
          azure-devops-token: ${{ EZTthOG1viZN9vNGl2MDve1hb1oVKq3D2uYvFpFVRGCeGZzTGG5xJQQJ99AKACAAAAAAAAAAAAASAZDO4gQr }} 
