name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t my-web-app .
        docker tag my-web-app ${{ secrets.DOCKER_USERNAME }}/my-web-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-web-app:latest

    - name: Deploy to Cloud (using Terraform)
      run: |
        terraform init
        terraform apply -auto-approve
