name: CI Pipeline

on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - master  # Trigger on pull requests to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use a virtual environment

    steps:
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up a specific environment (Node.js for a web app, for example)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version

    # 3. Install dependencies
    - name: Install dependencies
      run: npm install

    # 4. Build the application
    - name: Build the application
      run: npm run build

    # 5. Run tests (unit or integration tests)
    - name: Run tests
      run: npm test
